tasks:
  - init: yarn install
    command: yarn start

# list the ports to be exposed
ports:
  - port: 3000
    onOpen: open-preview
  - port: 3001
    onOpen: ignore

vscode:
  extensions:
    - syler.sass-indented@1.6.7:gAbIL/5IWvH0xYAbwe0Vag==
